version: '3.8'

services:
  # Frontend en Angular con Nginx
  frontend_pizzeria:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - app_pizzeria
    restart: always

  # Backend en Flask
  app_pizzeria:

    build: .
    ports:
      - "5000:5000"
    environment:
      environment:
      - DATABASE_URL=postgresql://pizzaadmin:Java**2025@pizzaos-db.postgres.database.azure.com:5432/postgres?sslmode=require
    depends_on:
      - db_pizzeria


  # La base de datos (como la que ya probamos)
  db_pizzeria:
    image: postgres:15
    environment:
      POSTGRES_USER: camilo_admin
      POSTGRES_PASSWORD: pizzapassword
      POSTGRES_DB: pizzeria_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: